######################################################################
# Automatically generated by qmake (3.0) Sun Jun 22 13:46:47 2014
######################################################################

TEMPLATE = app
TARGET = example
INCLUDEPATH += .
LIBS = -ldxfrw
QT += core gui printsupport qml
# Input
HEADERS += dxfrw_intf.h \
    implementation.h
SOURCES += main.cpp \
    implementation.cpp
